USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS RAYDP_SIS_ROLE;

GRANT ROLE RAYDP_SIS_ROLE to ROLE SYSADMIN;

GRANT ROLE RAYDP_SIS_ROLE to USER PLAKHANPAL;

USE ROLE SYSADMIN;

GRANT CREATE DATABASE ON ACCOUNT TO ROLE RAYDP_SIS_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE RAYDP_SIS_ROLE WITH GRANT OPTION;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE RAYDP_SIS_ROLE WITH GRANT OPTION;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE RAYDP_SIS_ROLE;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE RAYDP_SIS_ROLE WITH GRANT OPTION;
Grant usage on integration  ALLOW_ALL_NETWORK_EAI to role RAYDP_SIS_ROLE WITH GRANT OPTION;